/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.NhanVienModel;
import Services.Implements.NhanVienImp;
import Services.NhanVienSer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class FormQLNhanVien extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private NhanVienSer NVSer = new NhanVienImp();
    private List<NhanVienModel> ListNV = new ArrayList<>();

    /**
     * Creates new form FormQLNhanVien
     */
    public FormQLNhanVien() {
        initComponents();
        TBbang.setModel(dtm);
        String[] headers = {"Ma NV", "Ten NV", "SDT", "Ngay Sinh", "Ma Luong", "Ma TK"};
        dtm.setColumnIdentifiers(headers);
        ListNV = NVSer.getAll();
        LoadData(ListNV);
    }

    private void LoadData(List<NhanVienModel> ListNVS) {
        dtm.setRowCount(0);
        for (NhanVienModel nv : ListNVS) {
            dtm.addRow(nv.toDataRow());
        }
    }

    private void showData(NhanVienModel Nv) {
        txtMaNV.setText(Nv.getMaNV());
        txtTenNV.setText(Nv.getTenNV());
        txtSDT.setText(String.valueOf(Nv.getSdt()));
        txtNgaySinh.setText(Nv.getNgaySinh());
        txtMaluong.setText(Nv.getMaLuong());
        TxtMaTk.setText(Nv.getMaTk());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        BtHuy = new javax.swing.JButton();
        BtSua = new javax.swing.JButton();
        BtXoa = new javax.swing.JButton();
        BtLuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBbang = new javax.swing.JTable();
        BtSapXep = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMaluong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtMaTk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Thông tin nhân viên");

        txtMaNV.setBackground(new java.awt.Color(192, 215, 209));

        jLabel3.setText("Mã NV :");

        jLabel4.setText("Tên NV :");

        txtTenNV.setBackground(new java.awt.Color(205, 218, 218));

        jLabel5.setText("SĐT :");

        jLabel6.setText("Ngày Sinh :");

        txtSDT.setBackground(new java.awt.Color(204, 224, 226));

        txtNgaySinh.setBackground(new java.awt.Color(198, 216, 224));

        BtHuy.setBackground(new java.awt.Color(255, 255, 204));
        BtHuy.setText("Hủy");
        BtHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHuyActionPerformed(evt);
            }
        });

        BtSua.setBackground(new java.awt.Color(255, 204, 255));
        BtSua.setText("Sửa");
        BtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSuaActionPerformed(evt);
            }
        });

        BtXoa.setBackground(new java.awt.Color(255, 102, 102));
        BtXoa.setText("Xóa");
        BtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtXoaActionPerformed(evt);
            }
        });

        BtLuu.setBackground(new java.awt.Color(153, 255, 204));
        BtLuu.setText("Lưu NV");
        BtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLuuActionPerformed(evt);
            }
        });

        TBbang.setBackground(new java.awt.Color(245, 220, 183));
        TBbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "SĐT", "Ngày Sinh", "Mã Lương"
            }
        ));
        TBbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBbang);

        BtSapXep.setBackground(new java.awt.Color(204, 255, 255));
        BtSapXep.setText("Sắp Xếp");
        BtSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSapXepActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("----------------Danh Sách Nhân Viên----------------");

        txtMaluong.setBackground(new java.awt.Color(153, 255, 153));

        jLabel8.setText("Ma Luong :");

        jLabel9.setText("Ma Tk :");

        TxtMaTk.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(20, 20, 20)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                .addComponent(txtTenNV))
                                            .addComponent(txtMaluong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(219, 219, 219)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TxtMaTk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(102, 102, 102))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtSapXep)
                        .addGap(18, 18, 18)
                        .addComponent(BtHuy)
                        .addGap(18, 18, 18)
                        .addComponent(BtSua)
                        .addGap(28, 28, 28)
                        .addComponent(BtXoa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(TxtMaTk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtHuy)
                    .addComponent(BtSua)
                    .addComponent(BtXoa)
                    .addComponent(BtSapXep)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(BtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSuaActionPerformed
        // TODO add your handling code here:
        NhanVienModel NvU = ListNV.get(TBbang.getSelectedRow());
        String maNV = txtMaNV.getText();
        String tenNV = txtTenNV.getText();
        String Sdt = txtSDT.getText();
        String ngaySinh = txtNgaySinh.getText();
        String maLuong = txtMaluong.getText();
        String maTk = TxtMaTk.getText();
        NhanVienModel Nv = new NhanVienModel(maNV, tenNV, Integer.valueOf(Sdt), ngaySinh, maLuong, maTk);
        JOptionPane.showMessageDialog(rootPane, NVSer.Update(Nv, NvU.getMaNV()));
        ListNV = NVSer.getAll();
         LoadData(ListNV);
        
    }//GEN-LAST:event_BtSuaActionPerformed
    public void resetForm() {
        txtMaNV.setText("");
        txtTenNV.setText("");
        txtSDT.setText("");
        txtNgaySinh.setText("");
        txtMaluong.setText("");
        TxtMaTk.setText("");
    }
    private void BtHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHuyActionPerformed
        // TODO add your handling code here:
        resetForm();
        JOptionPane.showMessageDialog(this, "Hủy Thêm NV ❌");
    }//GEN-LAST:event_BtHuyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Exit... 🙋‍♂️");
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSapXepActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sắp Xếp Theo Mã NV 🔁 !");
        //Sắp xếp theo Mã NV
        ListNV.sort((o1, o2) -> {
            return o1.getMaNV().compareTo(o2.getMaNV());
        });
        LoadData(ListNV);
    }//GEN-LAST:event_BtSapXepActionPerformed

    private void TBbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBbangMouseClicked
        // TODO add your handling code here:
        NhanVienModel Nv = ListNV.get(TBbang.getSelectedRow());
        showData(Nv);
    }//GEN-LAST:event_TBbangMouseClicked

    private void BtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtXoaActionPerformed
        String maNV = txtMaNV.getText();
        JOptionPane.showMessageDialog(rootPane, NVSer.delete(maNV));
        ListNV = NVSer.getAll();
        LoadData(ListNV);
    }//GEN-LAST:event_BtXoaActionPerformed

    private void BtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLuuActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText();
        String tenNV = txtTenNV.getText();
        String SDT = txtSDT.getText();
        String NgaySinh = txtNgaySinh.getText();
        String maLuong = txtMaluong.getText();
        String maTk = TxtMaTk.getText();
        NhanVienModel Nv = new NhanVienModel(maNV, tenNV, Integer.valueOf(SDT), NgaySinh, maLuong, maTk);
        JOptionPane.showMessageDialog(this, NVSer.add(Nv));
        ListNV = NVSer.getAll();
        LoadData(ListNV);
    }//GEN-LAST:event_BtLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtHuy;
    private javax.swing.JButton BtLuu;
    private javax.swing.JButton BtSapXep;
    private javax.swing.JButton BtSua;
    private javax.swing.JButton BtXoa;
    private javax.swing.JTable TBbang;
    private javax.swing.JTextField TxtMaTk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaluong;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
